
# Generated by Django 3.2.9 on 2021-11-18 03:24


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('actors', models.CharField(max_length=100, null=True)),
                ('director', models.CharField(max_length=50, null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('wordcloud', models.ImageField(blank=True, upload_to='')),
                ('genres', models.ManyToManyField(related_name='movie', to='movies.Genre')),
                ('want_users', models.ManyToManyField(related_name='want_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
